[package]
name = "scylla-cdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = "0.2.1"
tokio = { version = "1.1.0", features = ["rt", "io-util", "net", "time", "macros", "sync"] }
chrono = "0.4.19"
futures = "0.3.17"
uuid = { version = "0.8.2", features = ["v1"] }

[dev-dependencies]
hex = "0.4.3"
